### ISSUE TITLE
Build architecture 64 bits

### ISSUE THREAD

**Issue by aloumeau-hager** [alfredh/baresip-android#12]
Hello thanks for this work!

i would like to build for armv8-a and x86_64 but no one of my tests was a success 

some help will be really apreciate for build it.

thanks

P.S: for the moment i think the most diffictult is to build openssl for this architecture

**Comment by aloumeau-hager** [comment]
No new for moment, i'm still searching solution

**Comment by alfredh** [comment]
at the moment we only support armv7-a architecture.
