### ISSUE TITLE
Audio output

### ISSUE THREAD

**Issue by aloumeau-hager** [alfredh/baresip-android#13]
Hello, i'm using baresip-android and i'm not a pro ;p ....
But i have a little problem, i saw that baresip play audio in media stream (channel) of android.
So i would like to have it in call stream to be able to enable handfree speaker and manage it from call volume.

I have no idea of where starting. 
Even if somebody have a little idea of where starting, it will be nicely to help me.

thanks in advance and sorry for my english.

**Comment by alfredh** [comment]
do you still have this problem ?

could you please describe your case in a bit more details ..


Alfred
