### ISSUE TITLE
retest not available

### ISSUE THREAD

**Issue by wsat** [alfredh/baresip-android#15]
The sources for retest are not available anymore. Any advise on how to create a test program for android?

**Comment by alfredh** [comment]
I uploaded a new retest sources tarball to:

http://www.creytiv.com/pub/

* retest is testing libre
* selftest is testing baresip

To build and execute the test programs:


```
$ make test
```

or 

```
$ make selftest
```


Alfred

**Comment by wsat** [comment]
Great. Thank you
________________________________
Von: Alfred E. Heggestad <notifications@github.com>
Gesendet: Donnerstag, 14. September 2017 17:00
An: alfredh/baresip-android
Cc: wsat; Author
Betreff: Re: [alfredh/baresip-android] retest not available (#15)


I uploaded a new retest sources tarball to:

http://www.creytiv.com/pub/

  *   retest is testing libre
  *   selftest is testing baresip

To build and execute the test programs:

$ make test


or

$ make selftest


Alfred

**Comment by wsat** [comment]
Thanks for this.


That worked well (with one exception: Make test fails because of


src/dtmf.c:39: error: undefined reference to 'dtmf_dec_alloc'
src/dtmf.c:51: error: undefined reference to 'dtmf_dec_probe'

make selftest worked,

Cheers


________________________________
Von: Alfred E. Heggestad <notifications@github.com>
Gesendet: Donnerstag, 14. September 2017 17:00
An: alfredh/baresip-android
Cc: wsat; Author
Betreff: Re: [alfredh/baresip-android] retest not available (#15)


I uploaded a new retest sources tarball to:

http://www.creytiv.com/pub/

  *   retest is testing libre
  *   selftest is testing baresip

To build and execute the test programs:

$ make test


or

$ make selftest


Alfred

**Comment by alfredh** [comment]
can you please try again with the latest version of librem:

http://www.creytiv.com/pub/rem-0.5.2.tar.gz


/Alfred

**Comment by wsat** [comment]
Thank you. Will do.

One thing I noticed: the only solution for Android video seems to be using gstreamer. Which feels like an overkill. Is there a way to render an h264 encoded rtp stream on android with less complexity?

Maybe using something similar to the iOS openGLES implementation from the modules directory?
Maybe combining it with Android's java media player?
A lightweight example would be great...

Many thanks
Walter

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by wsat** [comment]
Hi,

I had a chance to test the latest sources (0.5.6). Compiling for android remains a challenge:
1) openssl make script fails. I had to compile openssl using the instructions from here: 
https://wiki.openssl.org/index.php/Android; that solved the problem for me. I assume this is because android has changed the structure of the NDK (its now located in .../Sdk/ndk-bundle adn the header files ahve a somewhat different structure (I am compiling against android-21)

2) compiling modules/opengles fails. 
The module.mk file does link with the android NDK specific opngles libraries. Adding to LFLAGS -lGLESv1_CM which is the OpenGLES V1 specific librarie leads to the least number of undefined references but is still not working.

3) compiling test fails:
src/dtmf.c:39: error: undefined reference to 'dtmf_dec_alloc' 
src/dtmf.c:51: error: undefined reference to 'dtmf_dec_probe' 

Many thanks

**Comment by alfredh** [comment]
Regarding 1.) you need to use OpenSSL 1.1.0f or later.

Regarding 3.) you need to use latest librem from:
http://www.creytiv.com/pub/rem-0.5.2.tar.gz

Alfred

**Comment by wsat** [comment]
Ad 1) I am using OpenSSL 1.0.2m
Ad 2) Any suggestions? Many thanks!
Ad 3) Thank you!

**Comment by alfredh** [comment]
You should now use OpenSSL 1.1.0g, I think older versions will not build anymore.

I just compiled the whole project with NDK r14 and platform 17, it builds clean
without any warnings or errors.

the opengles module is not included in the default build. At the moment it
is probably not working at all. Testing opengles needs an Android application
with graphics to test, I dont have access to this anymore.

if you want to fix the opengles module, I would suggest that you open a new Issue
only for that.

This issue can be closed now.

**Comment by wsat** [comment]
Thanks for sharing your setup. I am now using 

- android platform 17 
- android-ndk-14r
- baresip-0.5.6
- re-0.5.6
- rem-0.5.2

Baresip compiles without error, but 'make test' fails with

> test 42 -- test_json
> 
> json: TEST_EQUALS: src/json.c:450: test_json_exponent(): expected=3(0x3), actual=4(0x4)
> test: test_json: test failed (Invalid argument)
> Failed (Invalid argument)
> 

Btw
I also tried using re-0.5.5, but using this version 'make test' failed at test_http_loop, TEST_EQUALS: src/http.c:147: http_req_handler(): expected=0(0x0), actual=824919605(0x312b4635)

**Comment by alfredh** [comment]
you also need latest `retest`:

http://www.creytiv.com/pub/retest-0.5.2.tar.gz

**Comment by wsat** [comment]
The latest version of retest on http://www.creytiv.com/pub/ seems to be 0.5.1

**Comment by wsat** [comment]
Thanks, I saw the update on the website! It now compiles and tests without any problem.

I will now try to integrate this into an Android Studio project and then play around with the opengles module but honestly, I have no clue where to start and how to connect the native opengles library with the rest of the Android application  (see and limited time to do so.

Any advice of how to go about it would be appreciated.

**Comment by alfredh** [comment]
okay. as I said, please open a new Issue for the opengles work.
