### ISSUE TITLE
dtmfio missing from EXTRA_MODULES

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip-android#16]
Default config created by first time start of baresip tries to load module_app dtmfio, but that module
is not complied by default by 'make baresip'.  I therefore added dtmfio to Makefile EXTRA_MODULES:

EXTRA_MODULES := dtmfio g711 stdio opensles dtls_srtp echo aubridge

**Comment by juha-h** [comment]
After I added dtmfio to EXTRA_MODULES and started baresip, module dtmfio was still not found.  I had to comment out its module_app line in config file.

**Comment by alfredh** [comment]
the dtmfio module is not required for basic operation, so I have commented it out
in the default config here:

https://github.com/alfredh/baresip/commit/7e49f82ec73630ba0c3678fd41768ba19395c8d9

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> the dtmfio module is not required for basic operation, so I have
> commented it out in the default config here:

Good, thanks, Juha
