### ISSUE TITLE
'make openssl' fails with android-ndk-r16b

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip-android#18]
make of openssl fails with android-ndk-r16b, which is currently the latest version.  something has changed from r14b to r16b regarding include files.  'make openssl' gives:

/usr/local/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread -mandroid -fPIC --sysroot=/usr/local/android-ndk-r16b/platforms/android-17/arch-arm -Wa,--noexecstack  -fPIC -DOPENSSL_USE_NODELETE -c -o crypto/aes/aes_core.o crypto/aes/aes_core.c
crypto/aes/aes_core.c:39:20: fatal error: assert.h: No such file or directory
 #include <assert.h>
                    ^
compilation terminated.

assert.h does exist in ./sysroot/usr/include/assert.h, but is not found by gcc.

Perhaps a note should be added to README.md to use android-ndk-r14b until someone figures out how to modify baresip-android Makefile.

**Comment by juha-h** [comment]
juha-h writes:

> assert.h does exist in ./sysroot/usr/include/assert.h, but is not
> found by gcc.

In r14b the include files are also included in all platform dirs:

/usr/local/android-ndk-r14b$ find . -name assert.h -print
./sysroot/usr/include/assert.h
./sources/cxx-stl/stlport/stlport/assert.h
./platforms/android-13/arch-arm/usr/include/assert.h
./platforms/android-13/arch-x86/usr/include/assert.h
./platforms/android-13/arch-mips/usr/include/assert.h
./platforms/android-22/arch-arm/usr/include/assert.h
./platforms/android-22/arch-mips64/usr/include/assert.h
./platforms/android-22/arch-x86/usr/include/assert.h
./platforms/android-22/arch-mips/usr/include/assert.h
./platforms/android-22/arch-x86_64/usr/include/assert.h
./platforms/android-22/arch-arm64/usr/include/assert.h
...

which explains why they are found.

**Comment by saket424** [comment]
Confirmed that with ndk r15c Makefile works but when ndk r16b is used, we get include file not found errors

**Comment by alfredh** [comment]
The Android NDK has changed to Unified Headers:

https://android.googlesource.com/platform/ndk.git/+/master/docs/UnifiedHeaders.md

In r16b there now only a single set of system headers that is used for all API levels.

what needs to be done:

* change sysroot to the new location of unified headers
* define __ANDROID_API__=XX in CFLAGS
* we should probably also change from gcc to clang

Alfred

**Comment by alfredh** [comment]
@saket424 could you please try the following commands and send me the output:

```
make test
make selftest
```

(Remember to connect Android device first)

**Comment by alfredh** [comment]
hi @juha-h 

I have added support for NDK r16b in this branch:

https://github.com/alfredh/baresip-android/tree/android_ndk_r16b

it should now support r15 and r16 

could you please test it ?


Alfred

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I have added support for NDK r16b in this branch:
> 
> https://github.com/alfredh/baresip-android/tree/android_ndk_r16b
> 
> it should now support r15 and r16 
> 
> could you please test it ?

I was able to build baresip, but make of optional opus, speex, and zrtp
fail.  'make opus', for example, produces:

checking for arm-linux-androideabi-gcc... /usr/local/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot /usr/local/Android/Sdk/ndk-bundle/sysroot
checking whether the C compiler works... no
configure: error: in `/usr/src/baresip-android/opus':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:194: recipe for target 'opus' failed
make: *** [opus] Error 77

and config.log has:

...
configure:3523: /usr/local/Android/Sdk/ndk-bundle/toolchains/arm-linux-androidea
bi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot /usr/local/
Android/Sdk/ndk-bundle/sysroot -V >&5
arm-linux-androideabi-gcc: error: unrecognized command line option '-V'
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
configure:3534: $? = 1
configure:3523: /usr/local/Android/Sdk/ndk-bundle/toolchains/arm-linux-androidea
bi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot /usr/local/
Android/Sdk/ndk-bundle/sysroot -qversion >&5
arm-linux-androideabi-gcc: error: unrecognized command line option '-qversion'
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
...

I used ndk r16b that is included in latest android-studio Android (in
directory Android/Sdk/ndk-bundle), because I don't currently have enough
disk space for standalone android-ndk-r16b.

Looks like Makefile entries for opus. speex and zrtp also need
updating.

-- Juha

**Comment by alfredh** [comment]
Thanks for testing :)

it looks like the new sysroot in android ndk is split into 2 parts;
one for headers and one for libraries.

I made some fixes in the branch, please git pull and try again.

(commit 5e6b03e5faf091fbb750af920582afb19ca3cd82)

**Comment by juha-h** [comment]
Alfred,

I made progress on this issue.  Below are the diffs to your Makefile
after which I got libbaresip.a build working using ndk-r16 that is in
Android/Sdk/ndk-bundle (should be the same as the standalone).
I also made the upgrade to speex build.

The main change is that I had to change -fPIE CFLAG to -fPIC.  With
-fPIE baresip application build failed with a note that instructed to
recompile with -fPIC.

openssl compilation still produced lots of these kind of warnings

/usr/local/Android/Sdk/ndk-bundle/sysroot/usr/include/stdlib.h:229:1: warning: 'annotate' attribute directive ignored [-Wattributes]

but they don't see to cause any harm.

One more thing: compilation of my android application failed in
re/include/re_types.h like this:

Error:(52, 18) error: typedef redefinition with different types ('long'
vs '__kernel_ssize_t' (aka 'int'))
Error:(59, 18)  typedef redefinition with different types ('uint32_t'
(aka 'unsigned int') vs '__socklen_t' (aka 'int'))
Error:(52, 18) error: typedef redefinition with different types ('long'
vs '__kernel_ssize_t' (aka 'int'))
Error:(59, 18) error: typedef redefinition with different types
('uint32_t' (aka 'unsigned int') vs '__socklen_t' (aka 'int'))

I "solved" the issue by rewriting the typedefs like this:

#ifndef __ssize_t_defined
typedef __kernel_ssize_t ssize_t;
/* typedef long     ssize_t; */
#define __ssize_t_defined
#endif

#ifndef WIN32
typedef __socklen_t socklen_t;
/* typedef uint32_t socklen_t; */
#endif

Perhaps some more general solution is needed?

Is it OK for you to apply the patch below to your Makefile?

-- Juha

-----------------------------------------------------------------------

*** Makefile.Alfred	2018-02-20 10:14:46.962310743 +0200
--- Makefile	2018-02-20 20:56:17.297807195 +0200
***************
*** 71,77 ****
  	-I$(PWD)/libzrtp/third_party/bnlib \
  	-I$(PWD)/libzrtp/third_party/bgaes \
  	-march=armv7-a \
! 	-fPIE \
  	-DCONFIG_PATH='\"$(CONFIG_PATH)\"'
  
  LFLAGS    := -L$(SYSROOT)/usr/lib/ \
--- 73,79 ----
  	-I$(PWD)/libzrtp/third_party/bnlib \
  	-I$(PWD)/libzrtp/third_party/bgaes \
  	-march=armv7-a \
! 	-fPIC \
  	-DCONFIG_PATH='\"$(CONFIG_PATH)\"'
  
  LFLAGS    := -L$(SYSROOT)/usr/lib/ \
***************
*** 197,203 ****
  	-isystem $(SYSROOT_INC)/usr/include/ \
  	-isystem $(SYSROOT_INC)/usr/include/$(TRIPLE) \
  	-march=armv7-a \
! 	-fPIE
  
  .PHONY: opus
  opus:
--- 199,205 ----
  	-isystem $(SYSROOT_INC)/usr/include/ \
  	-isystem $(SYSROOT_INC)/usr/include/$(TRIPLE) \
  	-march=armv7-a \
! 	-fPIC
  
  .PHONY: opus
  opus:
***************
*** 213,224 ****
  		mkdir include_opus/opus && \
  		cp include/* include_opus/opus
  
  .PHONY: speex
  speex:
  	cd speex && \
  		CC="$(CC) --sysroot $(SYSROOT)" \
  		RANLIB=$(RANLIB) AR=$(AR) PATH=$(BIN):$(PATH) \
! 		./configure --host=arm-linux-androideabi --disable-shared CFLAGS="-march=armv7-a" && \
  		CC="$(CC) --sysroot $(SYSROOT)" \
  		RANLIB=$(RANLIB) AR=$(AR) PATH=$(BIN):$(PATH) \
  		make
--- 215,233 ----
  		mkdir include_opus/opus && \
  		cp include/* include_opus/opus
  
+ SPEEX_CFLAGS    := \
+ 	-D__ANDROID_API__=$(API_LEVEL) \
+ 	-isystem $(SYSROOT_INC)/usr/include/ \
+ 	-isystem $(SYSROOT_INC)/usr/include/$(TRIPLE) \
+ 	-march=armv7-a \
+ 	-fPIC
+ 
  .PHONY: speex
  speex:
  	cd speex && \
  		CC="$(CC) --sysroot $(SYSROOT)" \
  		RANLIB=$(RANLIB) AR=$(AR) PATH=$(BIN):$(PATH) \
! 		./configure --host=arm-linux-androideabi --disable-shared CFLAGS="$(SPEEX_CFLAGS)" && \
  		CC="$(CC) --sysroot $(SYSROOT)" \
  		RANLIB=$(RANLIB) AR=$(AR) PATH=$(BIN):$(PATH) \
  		make
***************
*** 228,234 ****
  	-isystem $(SYSROOT_INC)/usr/include/ \
  	-isystem $(SYSROOT_INC)/usr/include/$(TRIPLE) \
  	-march=armv7-a \
! 	-fPIE
  
  .PHONY: zrtp
  zrtp:
--- 237,243 ----
  	-isystem $(SYSROOT_INC)/usr/include/ \
  	-isystem $(SYSROOT_INC)/usr/include/$(TRIPLE) \
  	-march=armv7-a \
! 	-fPIC
  
  .PHONY: zrtp
  zrtp:

**Comment by alfredh** [comment]
https://developer.android.com/ndk/guides/standalone_toolchain.html

```
# Tell configure what flags Android requires.
export CFLAGS="-fPIE -fPIC"
export LDFLAGS="-pie"
```

I think we should get the PIE/PIC thing working first in a separate commit,
and the NDK upgrade should be done in a separate commit.

BTW: Are you using the SPEEX codec actively? Since Jean-Marc has deprecated
it from speex.org I think we should deprecate/remove it (Everybody is using opus).


Alfred

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> https://developer.android.com/ndk/guides/standalone_toolchain.html
> 
> ```
> # Tell configure what flags Android requires.
> export CFLAGS="-fPIE -fPIC"
> export LDFLAGS="-pie"
> ```
> 
> I think we should get the PIE/PIC thing working first in a separate commit,
> and the NDK upgrade should be done in a separate commit.

In the baresip Makefile there was only -fPIE CFLAGS.  I replaced that
with -fPIC and got the app working.  I'll try later today what happens
when both are present as described in the above.
> 
> BTW: Are you using the SPEEX codec actively? Since Jean-Marc has deprecated
> it from speex.org I think we should deprecate/remove it (Everybody is
> using opus)

OPUS is pretty new and not yet supported by all SIP UAs.  But if speex
it is now deprecated, we can leave it out from the Android Makefile.

-- Juha

**Comment by alfredh** [comment]
please re-test with commit 9f0f1adc61483da40fa5a7c6d602fef88374f32a

I have made a couple of changes there.

as for getting it to work with r15 or r16:

* we need to add a new target to generate the toolchain
* we should use clang which automatically sets the ANDROID_API macro
* we just need to split the SYSROOT into one for headers and one for libs

I am almost on top of this, just needed to start again from scratch
a couple of times.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> as for getting it to work with r15 or r16:
> 
> * we need to add a new target to generate the toolchain
> * we should use clang which automatically sets the ANDROID_API macro
> * we just need to split the SYSROOT into one for headers and one for
> * libs

Perhaps it would suffice that make works only with r16, since I don't
see a point of using an old version of ndk.

-- Juha

**Comment by alfredh** [comment]
hi @juha-h 

could you please try now with commit 1290b36e62fb462f899bd7999fdc8b3b0b1a2629 ?

this should work with both r15 and r16

you need to override the `NDK_PATH` when invoking make
(or modify it in the makefile).

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> could you please try now with commit
> 1290b36e62fb462f899bd7999fdc8b3b0b1a2629 ?

I gave it a try using r16. Build of libbaresip.a and the android app
went fine.  However, when I placed a call, baresip terminated it with
error:

02-24 14:54:37.717  8721  8740 D Baresip : audio: start_source failed (opensles.nil): No such device

I have seen this before and I don't think it has anything to do with the
Makefile.  opensles module compiled fine:

  CC [m]  build-arm/modules/opensles/opensles.o
  CC [m]  build-arm/modules/opensles/player.o
  CC [m]  build-arm/modules/opensles/recorder.o


I need to figure out why the error comes and then keep on testing the
Makefile.  Any ideas?

-- Juha

**Comment by alfredh** [comment]
Great, thanks for testing!

You can try to do a complete clean build (remove src/static.c)

I just tested with a clean build using r16b and it works on my android phone:

```
call: connecting to 'sip:openwrt@10.0.0.4'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: source started with sample format S16LE
audio tx pipeline:    opensles ---> vumeter ---> PCMU
audio rx pipeline:    opensles <--- vumeter <--- PCMU
aeh@10.0.0.4: Call established: sip:openwrt@10.0.0.4
stream: incoming rtp for 'audio' established, receiving from 10.0.0.6:12284
sip:openwrt@10.0.0.4: session closed: Connection reset by peer=========      ]  [==============  ]
sip:aeh@10.0.0.4: Call with sip:openwrt@10.0.0.4 terminated (duration: 10 secs)
```

**Comment by juha-h** [comment]
juha-h writes:

> I gave it a try using r16. Build of libbaresip.a and the android app
> went fine.  However, when I placed a call, baresip terminated it with
> error:
> 
> 02-24 14:54:37.717  8721  8740 D Baresip : audio: start_source failed (opensles.nil): No such device

I have two Android devices to play with.  One has Android version 5.1
(API level 21) and the other has Android 7.1.1 (API level 23).

The Makefile has

API_LEVEL := 21

In build.gradle of the app I have

compileSdkVersion = 25
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 23

The above error does not appear when I run the app on the API level 21
device, but does appear on the API level 23 device.

-- Juha

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I just tested with a clean build using r16b and it works on my android
> phone:

As I mentioned in the previous post, It worked for me too on my 5.1
Android device, but not on my 7.1.1 device. What Android version do you
have?

-- Juha

**Comment by juha-h** [comment]
juha-h writes:

> I have two Android devices to play with.  One has Android version 5.1
> (API level 21) and the other has Android 7.1.1 (API level 23).

Now that I got access to the Internet, it turned out that 7.1.1 (where I
get the opensles error) has API level 25.

-- Juha

**Comment by alfredh** [comment]
my Android phone is:

```
shell@j5xnlte:/ $ getprop ro.build.version.release
6.0.1
shell@j5xnlte:/ $ getprop ro.build.version.sdk                                 
23
```

as a quick test, you can try to change API_LEVEL in the Makefile to the number
matching your phone, recompile everything, and do the test again to see if
it has any impact.

**Comment by juha-h** [comment]
Looks like something has changed regarding RECORD_AUDIO permission,
since I found that my api level 25 device produces these error messages
at call start:

02-25 19:42:25.794  3708  3975 W ServiceManager: Permission failure: android.permission.RECORD_AUDIO from uid=10185 pid=875
02-25 19:42:25.794  3708   877 D audio_hw_primary: in_standby: enter: stream (0xa6cb5680) usecase(7: audio-record)
02-25 19:42:25.795  3708  3975 E AudioFlingerSrvcUtils: Request requires android.permission.RECORD_AUDIO
02-25 19:42:25.795  3708  3975 E AudioFlinger: openRecord() permission denied: recording not allowed
02-25 19:42:25.795   842   842 E AudioRecord: AudioFlinger could not create record track, status: -1
02-25 19:42:25.802  3708  3977 D audio_hw_primary: adev_close_input_stream: enter:stream_handle(0xa6cb5680)
02-25 19:42:25.802  3708  3977 D audio_hw_primary: in_standby: enter: stream (0xa6cb5680) usecase(7: audio-record)
02-25 19:42:25.803   842   842 E libOpenSLES: android_audioRecorder_realize(0x8e5b9a00) error creating AudioRecord object; status -1
02-25 19:42:25.804   842   842 W libOpenSLES: Leaving Object::Realize (SL_RESULT_CONTENT_UNSUPPORTED)
02-25 19:42:25.804   842   859 D Baresip : audio: start_source failed (opensles.nil): No such device

I have in AndroidManifest.xml line

<uses-permission android:name="android.permission.RECORD_AUDIO" />

but that seems to be insufficient at newer API levels.

My conclusion thus is that the Makefile is OK and I need to figure out
how to solve the permission problem.

-- Juha

**Comment by juha-h** [comment]
juha-h writes:

> I have in AndroidManifest.xml line
> 
> <uses-permission android:name="android.permission.RECORD_AUDIO" />
> 
> but that seems to be insufficient at newer API levels.
> 
> My conclusion thus is that the Makefile is OK and I need to figure out
> how to solve the permission problem.

Problem solved based on this document:

https://developer.android.com/training/permissions/requesting.html#java

-- Juha

**Comment by alfredh** [comment]
@juha-h could you please confirm that the original issue is solved ?
(i.e. NDK upgrade)

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> @juha-h could you please confirm that the original issue is solved ?
> (i.e. NDK upgrade)

Yes, it is solved. Makefile works OK.

-- Juha
