### ISSUE TITLE
Instructions to build video-related EXTRA_MODULES for android

### ISSUE THREAD

**Issue by saket424** [alfredh/baresip-android#19]
Currently, the default Makefile does not seem to include any video codecs for android
EXTRA_MODULES="g711 stdio opensles dtls_srtp echo aubridge opus speex zrtp"

Any pointers in wiki or elsewhere on how to enable video-related EXTRA_MODULES ?

**Comment by saket424** [comment]
Preferably instructions for compiling the h265 baresip module on Android. Thanks in advance

**Comment by saket424** [comment]
I tried to enable opengles as an EXTRA_MODULE for android after changing the GLE include file path  and linker library to GLESv1_CM and am left with 3 undefined errors . 

modules/opengles/opengles.c:213: error: undefined reference to 'context_destroy'
modules/opengles/opengles.c:238: error: undefined reference to 'context_init'
modules/opengles/opengles.c:272: error: undefined reference to 'context_render'
collect2: error: ld returned 1 exit status

http://lists.creytiv.com/pipermail/re-devel/2016-June/000866.html

There is a modules/opengles/context.m file for iOS but no corresponding file in android. Anyone else get past this compilation issue and got video render working on android ?

**Comment by saket424** [comment]
while the opengles problems remain, I managed to compile baresip-android with video codec support using the docker container https://github.com/termux/termux-packages/blob/master/packages/ffmpeg/build.sh which has h264, h265, vp8 and vp9 support included also. Now if I can only figure out how to make videocalls on android :) same questions as noted in http://lists.creytiv.com/pipermail/re-devel/2017-August/001089.html

EXTRA_MODULES="g711 stdio opensles dtls_srtp echo aubridge fakevideo vp8 vp9 avcodec h265 vidloop opus speex zrtp"


nash:/data/local/tmp $ ./baresip
baresip v0.5.7 Copyright (C) 2010 - 2018 Alfred E. Heggestad et al.
Local network address:  IPv4=:192.168.155.232 
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
auplay: opensles
ausrc: opensles
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: VP8
vidcodec: VP9
h265: using x265 2.5 [Linux][clang 5.0.300080][32 bit][noasm] 8bit
vidcodec: H265
medianat: stun
medianat: turn
medianat: ice
Populated 0 accounts
account: No SIP accounts found
 -- check your config or add an account using 'uanew' command
Populated 3 contacts
Populated 3 audio codecs
Populated 1 audio filter
Populated 6 video codecs
Populated 0 video filters
baresip is ready.

**Comment by alfredh** [comment]
perhaps we should add a rule to the makefile for
cross-compiling ffmpeg for android ? that will enable
avcodec module (H.263, H.264, MPEG4 codecs).

which video drivers do you plan to use ?

**Comment by alfredh** [comment]
I will add rules for ffmpeg at some point. will reopen when starting the work.
