### ISSUE TITLE
is there means to turn on echo cancellation?

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip-android#24]
Issue https://github.com/juha-h/baresip-studio/issues/3 was opened on my baresip-studio project regarding echo cancellation on Android.  I vaguely remember that this has been discussed earlier, but could not find a trace.  What are the options?  I have seen mentioned Speex AEC, GStreamer, and somehow attaching Android AudioManager to the audio session.

**Comment by alfredh** [comment]
the best would be if Android has Hardware AEC. does anyone know if this is supported
by Android SW and/or HW ?

you can try the speex_aec module (Software AEC) but most likely it will not work
very well.

we should create a new module e.g. "webrtc_aec" that is using the AEC apis
from the Webrtc native project. This one has high quality AEC processing.


Alfred

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> the best would be if Android has Hardware AEC. does anyone know if
> this is supported by Android SW and/or HW ?

In Android API there is function to check if device implements AEC:

https://developer.android.com/reference/android/media/audiofx/AcousticEchoCanceler#isAvailable()

I guess it means hw AEC.  In order to use it, audioSession id is
needed.

> we should create a new module e.g. "webrtc_aec" that is using the AEC
> apis  from the Webrtc native project. This one has high quality AEC
> processing.

Sounds like a good option.

-- Juha

**Comment by juha-h** [comment]
There is some info about webrtc AEC native implementations on the web, e.g.

- https://stackoverflow.com/questions/12818721/webrtc-aec-on-android#14692832
- https://github.com/ThePacific/webrtc-android-jni

Also pjsip lib includes webrtc AEC:

- https://trac.pjsip.org/repos/ticket/1888

I'll add enhancement (feature request) label to this issue.

**Comment by henriz** [comment]
This might be a bit late, but you can use pulse, and in pulse configure the webrtc arc module. This works fine.

**Comment by juha-h** [comment]
@henriz Are you suggesting to use baresip pulse module in Android or something else?
