### ISSUE TITLE
armv8-a build guidelines for Android platform

### ISSUE THREAD

**Issue by avipintu** [alfredh/baresip-android#29]
We  would like to build for armv8-a for Android platform , Is there any guidelines available for the same .. 
Any suggestion would be of great help.. Thanks 

Thanking your for such nice work. 
Regards 
Pintu

**Comment by juha-h** [comment]
Pintu Lohar writes:

> We  would like to build for armv8-a for Android platform , Is there
> any guidelines available for the same ..  
> Any suggestion would be of great help.. Thanks

Ndk 19 has built-in toolchains for these arm architectures: armeabi-v7a
and arm64-v8a.  If armv8-a is the same as arm64-v8a, check
https://github.com/juha-h/libbaresip-android for hints.
