### ISSUE TITLE
About Android.mk file

### ISSUE THREAD

**Issue by giaotuancse** [alfredh/baresip-android#3]
Hi, 
I'm just a beginner in Android NDK and i'm trying to implement Baresip to my project. 
I followed the construction. Put 4 libraries were downloaded to jni folder. 
Them go to each folder run command "make".
Now I don't know how to config Android.mk file to build share library in this. Anyone can show me some ideas?

**Comment by hieudoan-ew** [comment]
@giaotuancse you should add one target for make file
```
libbaresip.so: Makefile librem.a libre.a
	@make $@ -C baresip $(COMMON_FLAGS) STATIC=1 \
	LIBRE_SO=$(PWD)/re LIBREM_PATH=$(PWD)/rem \
	EXTRA_MODULES="opensles" ANDROID=1
```
Run this command
`make libbaresip.so`

It will create libbaresip.so in baresip folder. Then you need create JNI wrapper by C to call baresip function. Some examples exist on test folder. It would help, I think :)
