### ISSUE TITLE
App crashes immediately after start

### ISSUE THREAD

**Issue by eldarbr** [alfredh/baresip-android#36]
Baresip crashes on start
I captured the log:
[log.txt](https://github.com/baresip/baresip-android/files/5790510/log.txt)
Build 25.0.0 (148) from f-droid
Android 9 (env emui 9.1)

**Comment by juha-h** [comment]
Eldar writes:

> Baresip crashes on start
> I captured the log:
> [log.txt](https://github.com/baresip/baresip-android/files/5790510/log.txt)
> Build 25.0.0 (148) from f-droid
> Android 9 (env emui 9.1)

I don't think this is related to baresip-android lib, but on how you use it.

**Comment by datadata95** [comment]
I get the exact same problem. After allowing baresip using the microphone, the app crashes and won't open again, also on Android. Got the app from Google Play.

**Comment by juha-h** [comment]
If you still have this issue, please open it in baresip-studio project.
