### ISSUE TITLE
Notification for unregistered usage.

### ISSUE THREAD

**Issue by golserma** [alfredh/baresip-android#39]
To save battery I'd like to just be able to start calls and not receive calls.
I have added a sip server and do not register. Do I still need the notification? If not can you please add an option to disable the notification? I use sip only for long distance calls noone is calling this number ever.

**Comment by juha-h** [comment]
golserma writes:

> To save battery I'd like to just be able to start calls and not receive calls.
> I have added a sip server and do not register. Do I still need the
> notification? If not can you please add an option to disable the
> notification? I use sip only for long distance calls noone is calling
> this number ever.

It would be for me a too big code change.  The very reason why I started
this project was to have an Android SIP app that can run in the
background and receive calls without Google's push notification service.

You can quit the app after you made the call or use Linphone that I
think has the option to turn off background mode.

**Comment by juha-h** [comment]
I just notice that you created this issue in wrong project.   Correct project is baresip-studio.  Anyway, at this moment I'm not planing to implement your feature request.

**Comment by golserma** [comment]
Thank you very much for your feedback :)
