### ISSUE TITLE
SYSROOT does not point to root

### ISSUE THREAD

**Issue by juha-h** [alfredh/baresip-android#5]
I tried to add zrtp build to Makefile, but got into complications, because SYSROOT does not point to root, but to /usr:

SYSROOT := $(NDK_PATH)/platforms/$(PLATFORM)/arch-arm/usr

Would it be OK to remove /usr from the end and append /usr to where $(SYSROOT) is currently used?

-- Juha

**Comment by alfredh** [comment]
yeah sure that should be fine. could you please create a PR for that ?

**Comment by alfredh** [comment]
I have merged the PRs to master now.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I have merged the PRs to master now.

Alfred,

Thanks.  For some reason, I don't need these, but they don't hurt
either:

-- Juha

jh@lohi:/usr/src/orig$ diff -c  -r baresip-android/Makefile baresip-android.fork/Makefile 
*** baresip-android/Makefile	2016-10-23 21:11:54.447205770 +0300
--- baresip-android.fork/Makefile	2016-10-23 16:36:35.367039951 +0300
***************
*** 47,54 ****
  	-I$(PWD)/opus/include_opus \
  	-I$(PWD)/speex/include \
  	-I$(PWD)/libzrtp/include \
- 	-I$(PWD)/libzrtp/third_party/bnlib \
- 	-I$(PWD)/libzrtp/third_party/bgaes \
  	-march=armv7-a \
  	-fPIE \
  	-DCONFIG_PATH='\"$(CONFIG_PATH)\"'
--- 47,52 ----
***************
*** 57,63 ****
  	-L$(PWD)/opus/.libs \
  	-L$(PWD)/speex/libspeex/.libs \
  	-L$(PWD)/libzrtp \
- 	-L$(PWD)/libzrtp/third_party/bnlib \
  	-fPIE -pie
  LFLAGS    += --sysroot=$(NDK_PATH)/platforms/$(PLATFORM)/arch-arm
  
--- 55,60 ----
